version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: docker/app/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: docker/ngnix/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80
    expose:
          - 6001

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=echo"
      - "MYSQL_USER=echo_user"
      - "MYSQL_PASSWORD=asd123"
      - "MYSQL_ROOT_PASSWORD=asd123"
    ports:
        - "33061:3306"

volumes:
  dbdata: